/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SquareColorImport } from './routes/square-color'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SquareColorRoute = SquareColorImport.update({
  path: '/square-color',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/square-color': {
      id: '/square-color'
      path: '/square-color'
      fullPath: '/square-color'
      preLoaderRoute: typeof SquareColorImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByPath
  fullPaths: '/' | '/square-color'
  fileRoutesByTo: FileRoutesByPath
  to: '/' | '/square-color'
  id: '__root__' | '/' | '/square-color'
  fileRoutesById: {
    __root__: typeof rootRoute
    '/': typeof IndexRoute
    '/square-color': typeof SquareColorRoute
  }
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SquareColorRoute: typeof SquareColorRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SquareColorRoute: SquareColorRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/square-color"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/square-color": {
      "filePath": "square-color.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
